mapper:
  updateCondition:
    type: distance
    value: 1.0

  sensorMaxRange: 80

  mapperModule:
    - PointDistanceMapperModule:
        minDistNewPoint: 0.1

input:

  - BoundingBoxDataPointsFilter:
      xMin: 1.0
      xMax: 1.0
      yMin: 1.0
      yMax: 1.0
      zMin: 1.0
      zMax: 1.0
      removeInside: 1

  - BoundingBoxDataPointsFilter:
      xMin: 1.5
      xMax: 6
      yMin: -2.5
      yMax: 2.5
      zMin: -1
      zMax: 1
      removeInside: 1

  - RandomSamplingDataPointsFilter:
      prob: 0.8

  - AddDescriptorDataPointsFilter:
      descriptorName: probabilityDynamic
      descriptorDimension: 1
      descriptorValues: [0.6]

  - SamplingSurfaceNormalDataPointsFilter:
      ratio: 0.5
      knn: 7
      samplingMethod: 0
      maxBoxDim: inf
      averageExistingDescriptors: 1
      keepNormals: 1
      keepDensities: 0
      keepEigenValues: 0
      keepEigenVectors: 0

icp:
  readingDataPointsFilters:
    - RandomSamplingDataPointsFilter:
        prob: 0.8

  referenceDataPointsFilters:
    - RandomSamplingDataPointsFilter:
        prob: 0.25

  outlierFilters:
    - TrimmedDistOutlierFilter:
        ratio: 0.9

  matcher:
    KDTreeMatcher:
      knn: 3
      epsilon: 1
      searchType: 1
      maxDist: 0.5

  errorMinimizer:
    PointToPlaneErrorMinimizer:
      force4DOF: 1

  transformationCheckers:
    - CounterTransformationChecker:
        maxIterationCount: 30
    - DifferentialTransformationChecker:
        minDiffRotErr: 0.001
        minDiffTransErr: 0.01
        smoothLength: 3

  inspector: NullInspector

  logger: NullLogger

post:
